connectedcars/node-vinutils

src/resolvers/get-fuel-type.js, src/resolvers/get-fuel-type.test.js
Bug in the previous release :(.
Fixed it, and added test case for future safety.
=> Fix bug in fuel type extraction

.gitignore, src/index.test.js, src/resolvers/get-year.js
Story details: https://app.clubhouse.io/connectedcars/story/2832
=> Stop trying to guess model year for other brands

src/resolvers/get-fuel-type.js, src/types/@connectedcars/vinutils/index.d.ts
overlooked type signature fixed
- will be minor bumped
=> fixing type of getFuelType

src/types/@connectedcars/vinutils/index.d.ts
[ch-36477]
[skip-ch]
Test in backend revealed some bugs
=> typo fixes in mirror type

src/types/@connectedcars/vinutils/index.d.ts
[ch-36477]
[skip-ch]
I promise it's good this time :)
=> additional typo fix

src/resolvers/get-fuel-type.js, src/resolvers/get-fuel-type.test.js
=> Adds fuel type resolving for TFSI e and ID.3

src/resolvers/get-fuel-type.js, src/resolvers/get-fuel-type.test.js
=> Adds mild hybrid check to fuel type resolver

src/constants/model.js, src/resolvers/get-model.js
=> Adds more models to VAG brands

src/constants/fuel-type.js, src/resolvers/get-fuel-type.js, src/resolvers/get-fuel-type.test.js, src/types/@connectedcars/vinutils/index.d.ts
[ch-55701]
[skip-ch]
The integration tests do not all pass (531 pending, 1179 failing) in code and tests that this PR has not touched. The same tests also fail on master so maybe this is expected?
=> Add hybrid diesel fuel type

src/constants/model.js, src/resolvers/get-model.js, src/resolvers/get-model.test.js, src/types/@connectedcars/vinutils/index.d.ts
=> Add Trafic to Renault models

src/constants/model.js, src/resolvers/get-model.js, src/resolvers/get-model.test.js, src/types/@connectedcars/vinutils/index.d.ts
=> Add Duster to Dacia models

src/constants/model.js, src/resolvers/get-model.js, src/resolvers/get-model.test.js, src/types/@connectedcars/vinutils/index.d.ts
=> Add SEAT Born model

src/constants/model.js, src/resolvers/get-model.js, src/resolvers/get-model.test.js, src/types/@connectedcars/vinutils/index.d.ts
=> Add new models

src/constants/model.js, src/resolvers/get-model.js, src/resolvers/get-model.test.js, src/types/@connectedcars/vinutils/index.d.ts
=> Add VW Taigo and MAN Lastbil models

src/index.test.js, src/resolvers/get-make.js
=> refactor(GetMake): W1V as Mercedes-Benz

src/constants/make.js, src/constants/model.js, src/resolvers/get-model.js, src/resolvers/get-model.test.js
=> Refactor(make): add 'Other' brand

.dockerignore, Dockerfile, cloudbuild.yaml, package-lock.json, package.json, src/resolvers/get-year.js
=> chore(Docker): add docker build to run tests

src/index.test.js, src/resolvers/get-fuel-type.js, src/resolvers/get-fuel-type.test.js
=> Refactor/get fuel type/separate by make

Dockerfile, package-lock.json, package.json
=> chore(): bump node version 16

src/constants/model.js, src/resolvers/get-model.js, src/resolvers/get-model.test.js
=> refactor(Models): add Tesla Model 3 and ID.5

src/resolvers/get-model.js, src/resolvers/get-model.test.js
=> feat(Models): add model Q4 to model resolvers

src/resolvers/get-fuel-type.js, src/resolvers/get-fuel-type.test.js
Part of [sc-83965]
[skip-sc]
| Repository |  Packages to bump |
|---|---|
|  https://github.com/connectedcars/node-backend/ |  `node-vinutils` |
|  https://github.com/connectedcars/vehicle-configs/ |  `node-vinutils` |
|  https://github.com/connectedcars/node-integration/ |  `node-vinutils`, `node-backend`|
|  https://github.com/connectedcars/integration/ |   `node-backend`, `node-integration` |
|  https://github.com/connectedcars/api/ |   `node-vinutils`, `node-backend`, `node-integration` |
|  https://github.com/connectedcars/notifier/ |   `node-vinutils`, `node-backend`, `node-integration` |
|  https://github.com/connectedcars/job-runner-rollouts/ |  `node-backend` |
|  https://github.com/connectedcars/job-runner-integration/ |  `node-backend` |
=> Add fuel type for skoda enyaq

src/constants/model.ts, src/resolvers/get-model.test.ts, src/resolvers/get-model.ts
[sc-91114]
| https://github.com/connectedcars/api/                    | `node-vinutils`, `node-backend`, …
=> Add more makes and models

src/resolvers/get-fuel-type.test.ts, src/resolvers/get-fuel-type.ts
=> Fixes parsing of fuelType field in resolver

src/constants/model.ts, src/resolvers/get-model.test.ts, src/resolvers/get-model.ts
[sc-98904] [skip-sc] I didn't add Taos and Teramont as they were already added.
| …
=> Add new models, remove Comfortline

src/constants/model.ts, src/resolvers/get-model.test.ts, src/resolvers/get-model.ts
[sc-95805]
[sc-96398]
[skip-sc] …
=> Resolve models for new makes

src/resolvers/get-model-from-vin.test.ts, src/resolvers/get-model-from-vin.ts, src/resolvers/get-model.ts
=> feature(Models): get model from vin

src/constants/model.ts, src/resolvers/get-model.test.ts, src/resolvers/get-model.ts, src/resolvers/get-year.ts
=> Cupra year and ix3

src/constants/model.ts, src/resolvers/get-model.test.ts, src/resolvers/get-model.ts
| https://github.com/connectedcars/node-backend/           | `node-vinutils`, `node-integration`, `vehicle-configs`|
| https://github.com/connectedcars/api/                    | `node-vinutils`, `node-backend`, …
=> Add several models

src/constants/model.ts, src/resolvers/get-make.ts, src/resolvers/get-model.test.ts, src/resolvers/get-model.ts
=> Add new models to node-vinutils

src/resolvers/get-model-from-vin.test.ts, src/resolvers/get-model-from-vin.ts, src/resolvers/get-model.test.ts, src/resolvers/get-model.ts
=> Fixes model matching for Tiguan/Transporter

src/constants/model.ts, src/resolvers/get-model.test.ts, src/resolvers/get-model.ts
| https://github.com/connectedcars/api/                    | `node-vinutils`, `node-backend`. …
=> Adds new models to Dacia, Porsche and Renault

src/constants/model.ts, src/resolvers/get-model.test.ts, src/resolvers/get-model.ts
| https://github.com/connectedcars/api/                    | `node-vinutils`, `node-backend`. …
=> Adds new BMW, Ford and Mazda models

src/constants/model.ts, src/resolvers/get-model.test.ts, src/resolvers/get-model.ts
=> Adds more models

src/constants/model.ts, src/resolvers/get-model.test.ts, src/resolvers/get-model.ts
=> Add XC60 and XC90 models

src/constants/model.ts, src/resolvers/get-model.test.ts, src/resolvers/get-model.ts
=> add peugeot 508
